function [t, q, u] = simulate(sys, con)
    % sys: a system (class object)
    % con: a controller (function)
    % t: time stampes (colv)
    % q: states (cols)
    % u: control inputs generated by controllers (cols)
    
    odefun = @(t,q) sys.dynamics(q, con(sys, q));
    [t, q] = ode45(odefun, sys.tspan, sys.initial);
    q = q';
    u = arrayfun(@(i) con(sys, q(:,i)), 1:size(t,1), 'UniformOutput', false);
    u = cell2mat(u);
end

